# Generated by Django 2.0 on 2018-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180516_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('PS', 'Start of Point'), ('DF', 'Defensive Stop'), ('TO', 'Offensive Turnover'), ('OT', 'Other')], default='PS', max_length=2),
        ),
    ]
